Setup of mobile-first portfolio
hydaline-code/Portfolio-Setup pull request #1
Opened 2023-01-13 13:16 UTC by hydaline-code

Here you will find my mobile first portfolio according to the Figma-template2 being my choice. Please Kindly review my work and give feedback thanks. The codes to see are mobile.html and mobile.css these are the mobile version files on which I worked.

2023-01-13 13:28 UTC, muneebulrehman reviewed
Hi @hydaline-code , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has failing linter checks

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-13 17:14 UTC, AbayomiOlaoye requested changes
Hi @hydaline-code  :wave: , 

Good job with this milestone so far!
There are just a few more issues to work on before moving on to the next project but you are almost there!

![so_close](https://user-images.githubusercontent.com/99715640/211950260-0e3881c0-9d4f-4ea2-a670-9ef45a23a0f5.gif)

## Highlights :dart: 

- Descriptive Pull Request message :heavy_check_mark: 
- Good use of GitHub flow :heavy_check_mark: 
- Meaningful commit messages :heavy_check_mark: 
- No linter error :heavy_check_mark: 

## Required Changes ♻️
- Kindly consider changing your `html` file to `index.html` instead of 'mobile.html` . This because search engine algorithms have preference for files named `index.html` has it considered your homepage. So in the long-run, it will improve for SEO visibility; then :point_down:

- ### _Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._ :pray: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 17:14 UTC, AbayomiOlaoye commented on mobile.html
> +          </div>
- [ ] Also, the use of `nav` tag is not really applicable because its children are not navigation elements. Please remove it and consider using an unordered list `ul`  to group these icons and each in a `li` tag. E.g.
```
        <ul>
            <li><a href="#"><img src="file_name" alt="text here"></a></li>
            <li><a href="#"><img src="file_name" alt="txt here"></a></li>
            <li><a href="#"><img src="file_name" alt="text here"></a></li>
            <li><a href="#"><img src="file_name" alt="text here"></a></li>
            <li><a href="#"><img src="file_name" alt="text here"></a></li>
        </ul>
```
- [ ] Please note that it is a good practice to always include descriptive texts in `alt` attribute of every `img` tag. It is good for users with screen readers users and also good for User experience, should the network fail to load properly. :memo:

2023-01-13 17:14 UTC, AbayomiOlaoye commented on mobile.css
> +* {
- [ ] Good job importing these required `font-families` but you did not use any of them in your design: Please compare the two designs below and see how to make it look like the figma design as it is a requirement for this project to be approved.

**Your design:**

![image](https://user-images.githubusercontent.com/99715640/212377424-a1a22dea-154d-4353-b4b6-e1ebcf4e775c.png)

**Figma design:**

![image](https://user-images.githubusercontent.com/99715640/212377541-11708f2b-674f-49d0-bdad-3fed04ba4cf3.png)

2023-01-13 18:20 UTC, hydaline-code commented on mobile.css
> +* {
hello thanks ... actually i used in but it was giving some errors after the code check then I removed it

2023-01-13 18:41 UTC, AbayomiOlaoye commented on mobile.css
> +* {
Ouch, sorry about that 🤦. I suggest you check what the problem really was. Linter will give you a report that details what the reason was. So that you will be able to meet the requirements. You will agree that those fonts make the site look nice, don't you? 

Let me know if you need more clarity on this please.

2023-01-14 09:10 UTC, frank1738 approved these changes
Hi @hydaline-code , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/FT0UFROtAbVEA/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error

## Optional suggestions


N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 10:35 UTC, merged