Contact feature for Portfolio
hydaline-code/Portfolio-Setup pull request #3
Opened 2023-01-24 15:16 UTC by hydaline-code

Hello everyone please here is the updated feature of the portfolio version which is the contact form. I followed the recommendations as follows for this part. I had a pair-program review. Please kindly do the code review so I can proceed to the adjustment for the final submission. Thanks

2023-01-24 15:29 UTC, frank1738 requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/hXz6GN0ZilLwhgLo49/giphy.gif"/>


## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ Form submission is working properly👍 



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-24 15:29 UTC, frank1738 commented on index.html
> +            <textarea name="text"  maxlength="500" placeholder="Enter text here" required /></textarea>
- [ ] Kindly style your `get in touch` button to match the original design. Also, adjust the padding around the texts in the `<textarea/>` 

![image](https://user-images.githubusercontent.com/98453979/214335166-2f69479e-08a7-4554-ace9-94c6d92d344d.png)

### Checkout the original design

![image](https://user-images.githubusercontent.com/98453979/214335377-914beb2d-c5b1-49fa-a2e6-08d0cc900c07.png)

2023-01-25 05:42 UTC, hydaline-code commented on index.html
> +            <textarea name="text"  maxlength="500" placeholder="Enter text here" required /></textarea>
hi, thanks it's done!

2023-01-25 05:50 UTC, Shedrack-Sunday approved these changes
Hi @hydaline-code    👋 
 
 # STATUS: APPROVED ✔️  🍾  🥳

 Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉

 ![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)
 
 ## Highlights
✔️  Proper use of Github features 💯 
✔️  well-crafted pull request 👍 
✔️ Linters are passing 👏 
 
 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._
 

 
 Cheers and Happy coding!👏👏👏
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 07:00 UTC, merged